#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Framework.Gameplay.Abilities.Editor
{
    /// <summary>创建能力配置、运行时数据和运行时脚本的编辑器工具。</summary>
    internal sealed partial class AbilityScriptCreatorWindow : EditorWindow
    {
        // 能力运行时数据语义键的源码资产路径。
        private const string RuntimeDataTypeAssetPath =
            "Assets/_Project/Scripts/CSharp/Core/Gameplay/GAS/Core/AbilityRuntimeDataType.cs";
        // 自动生成运行时数据键的开始标记。
        private const string RuntimeDataTypeGeneratedStartMarker = "        // <auto-generated>";
        // 自动生成运行时数据键的结束标记。
        private const string RuntimeDataTypeGeneratedEndMarker = "        // </auto-generated>";
        // 当前创建操作使用的目标文件夹资产路径。
        private string _targetFolderPath;
        // 当前待生成能力的 C# 类型名称。
        private string _abilityName = string.Empty;
        // 用于让窗口打开后直接编辑能力名称。
        private bool _focusAbilityName;

        /// <summary>验证目标文件夹后打开能力脚本创建窗口。</summary>
        [MenuItem("Tool/GAS/Create New Ability Scripts")]
        private static void OpenWindow()
        {
            if (!TryGetSelectedTargetFolder(out string targetFolderPath)) return;

            AbilityScriptCreatorWindow window =
                GetWindow<AbilityScriptCreatorWindow>("Create New Ability Scripts");
            window._targetFolderPath = targetFolderPath;
            window._abilityName = string.Empty;
            window._focusAbilityName = true;
            window.minSize = new Vector2(420f, 170f);
            window.ShowUtility();
        }

        /// <summary>绘制能力名称输入和脚本生成操作界面。</summary>
        private void OnGUI()
        {
            EditorGUILayout.LabelField("Create New Ability Scripts", EditorStyles.boldLabel);
            EditorGUILayout.Space(4f);
            EditorGUILayout.LabelField("Target Folder", _targetFolderPath ?? string.Empty);

            GUI.SetNextControlName("AbilityNameField");
            _abilityName = EditorGUILayout.TextField("Ability Name", _abilityName);
            if (_focusAbilityName)
            {
                EditorGUI.FocusTextInControl("AbilityNameField");
                _focusAbilityName = false;
            }

            EditorGUILayout.Space(8f);
            using (new EditorGUI.DisabledScope(string.IsNullOrWhiteSpace(_abilityName)))
            {
                if (GUILayout.Button("Create Scripts", GUILayout.Height(28f)))
                    CreateAbilityScripts();
            }
        }

        /// <summary>创建能力子文件夹并写入三份能力脚本。</summary>
        private void CreateAbilityScripts()
        {
            string abilityName = _abilityName.Trim();
            if (!IsValidAbilityName(abilityName, out string validationError))
            {
                ShowError(validationError);
                return;
            }

            if (!AssetDatabase.IsValidFolder(_targetFolderPath))
            {
                ShowError("目标文件夹已不存在，请重新选择一个 Assets 下的文件夹。");
                Close();
                return;
            }

            string abilityFolderPath = $"{_targetFolderPath}/{abilityName}";
            string[] fileNames = GetGeneratedFileNames(abilityName);
            string[] assetPaths = new string[fileNames.Length];
            for (int index = 0; index < fileNames.Length; index++)
                assetPaths[index] = $"{abilityFolderPath}/{fileNames[index]}";

            if (!ValidateRuntimeDataTypeRegistration(abilityName)) return;
            if (!ValidateOutputPaths(abilityFolderPath, assetPaths)) return;

            // 目标子文件夹不存在时由 AssetDatabase 创建，已存在时复用它。
            if (!AssetDatabase.IsValidFolder(abilityFolderPath))
            {
                AssetDatabase.CreateFolder(_targetFolderPath, abilityName);
                AssetDatabase.Refresh();
            }

            if (!AssetDatabase.IsValidFolder(abilityFolderPath))
            {
                ShowError($"无法创建能力文件夹：{abilityFolderPath}");
                return;
            }

            string absoluteFolderPath = AssetPathToAbsolutePath(abilityFolderPath);
            try
            {
                Directory.CreateDirectory(absoluteFolderPath);
                WriteGeneratedScripts(absoluteFolderPath, abilityName, fileNames);
                RegisterGeneratedRuntimeDataType(abilityName);
            }
            catch (Exception exception)
            {
                Debug.LogException(exception, this);
                ShowError($"生成能力脚本失败：{exception.Message}");
                return;
            }

            AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport);
            AssetDatabase.SaveAssets();
            SelectGeneratedFolder(abilityFolderPath, assetPaths[0]);
            Close();
        }

        /// <summary>验证输出文件夹和文件路径，避免覆盖已有代码。</summary>
        private bool ValidateOutputPaths(string abilityFolderPath, IReadOnlyList<string> assetPaths)
        {
            if (AssetDatabase.IsValidFolder(abilityFolderPath))
            {
                for (int index = 0; index < assetPaths.Count; index++)
                {
                    if (!File.Exists(AssetPathToAbsolutePath(assetPaths[index]))) continue;
                    ShowError($"目标文件已存在，生成已中止：{assetPaths[index]}");
                    return false;
                }
            }

            return true;
        }

        /// <summary>获取当前 Project 窗口选中的 Assets 文件夹。</summary>
        /// <param name="targetFolderPath">合法时返回选中文件夹的资产路径。</param>
        /// <returns>选中合法目标文件夹时返回 true。</returns>
        private static bool TryGetSelectedTargetFolder(out string targetFolderPath)
        {
            targetFolderPath = null;
            UnityEngine.Object selectedObject = Selection.activeObject;
            string selectedAssetPath = selectedObject == null
                ? null
                : AssetDatabase.GetAssetPath(selectedObject);

            if (string.IsNullOrWhiteSpace(selectedAssetPath) ||
                !selectedAssetPath.StartsWith("Assets", StringComparison.Ordinal) ||
                !AssetDatabase.IsValidFolder(selectedAssetPath))
            {
                ShowError("请先在 Project 窗口中选中 Assets 下的目标文件夹。");
                return false;
            }

            targetFolderPath = selectedAssetPath.Replace("\\", "/").TrimEnd('/');
            return true;
        }

        /// <summary>校验能力名称是否同时满足文件夹和 C# 类型命名要求。</summary>
        private static bool IsValidAbilityName(string abilityName, out string validationError)
        {
            if (string.IsNullOrWhiteSpace(abilityName))
            {
                validationError = "能力名称不能为空。";
                return false;
            }

            if (!IsIdentifierStart(abilityName[0]))
            {
                validationError = "能力名称首字符必须是英文字母或下划线。";
                return false;
            }

            for (int index = 1; index < abilityName.Length; index++)
            {
                if (IsIdentifierPart(abilityName[index])) continue;
                validationError = "能力名称只能包含英文字母、数字和下划线。";
                return false;
            }

            if (CSharpKeywords.Contains(abilityName))
            {
                validationError = $"能力名称不能使用 C# 关键字：{abilityName}。";
                return false;
            }

            validationError = null;
            return true;
        }

        /// <summary>将能力名称转换为配置、运行时数据和运行时脚本文件名。</summary>
        private static string[] GetGeneratedFileNames(string abilityName)
        {
            return new[]
            {
                $"{abilityName}AbilitySO.cs",
                $"{abilityName}AbilityRuntimeData.cs",
                $"{abilityName}AbilityRuntime.cs"
            };
        }

        /// <summary>写入能力配置、运行时数据和运行时脚本模板。</summary>
        private static void WriteGeneratedScripts(
            string absoluteFolderPath,
            string abilityName,
            IReadOnlyList<string> fileNames)
        {
            UTF8Encoding encoding = new UTF8Encoding(false);
            string[] contents =
            {
                BuildAbilitySO(abilityName),
                BuildAbilityRuntimeData(abilityName),
                BuildAbilityRuntime(abilityName)
            };

            for (int index = 0; index < fileNames.Count; index++)
            {
                string filePath = Path.Combine(absoluteFolderPath, fileNames[index]);
                File.WriteAllText(filePath, contents[index], encoding);
            }
        }

        /// <summary>向运行时数据类型枚举写入新能力的专用语义键。</summary>
        /// <param name="abilityName">已通过 C# 标识符校验的能力名称。</param>
        private static void RegisterGeneratedRuntimeDataType(string abilityName)
        {
            string runtimeDataTypePath = AssetPathToAbsolutePath(RuntimeDataTypeAssetPath);
            if (!File.Exists(runtimeDataTypePath))
                throw new FileNotFoundException("未找到能力运行时数据类型定义。", runtimeDataTypePath);

            string content = File.ReadAllText(runtimeDataTypePath);
            if (ContainsRuntimeDataType(content, abilityName)) return;
            if (ContainsReservedRuntimeDataType(content, abilityName))
                throw new InvalidOperationException(
                    $"能力名称 {abilityName} 与已有运行时数据键冲突，请更换能力名称。\n" +
                    "能力名不能复用 Input、Movement、Ground、Physics、Jump 或 FloatingCapsule。");
            if (!content.Contains(RuntimeDataTypeGeneratedStartMarker))
                throw new InvalidOperationException("能力运行时数据类型定义缺少自动生成区域开始标记。");
            if (!content.Contains(RuntimeDataTypeGeneratedEndMarker))
                throw new InvalidOperationException("能力运行时数据类型定义缺少自动生成区域结束标记。");

            // 将新键写入受控区域，保证多个自动生成能力不会共用 Custom 键。
            string entry = $"        {abilityName},{Environment.NewLine}";
            content = content.Replace(
                RuntimeDataTypeGeneratedEndMarker,
                entry + RuntimeDataTypeGeneratedEndMarker);
            File.WriteAllText(runtimeDataTypePath, content, new UTF8Encoding(false));
        }

        /// <summary>验证能力运行时数据键可以安全写入枚举源码。</summary>
        /// <param name="abilityName">已通过 C# 标识符校验的能力名称。</param>
        /// <returns>验证通过或已存在同名自动生成键时返回 true。</returns>
        private static bool ValidateRuntimeDataTypeRegistration(string abilityName)
        {
            string runtimeDataTypePath = AssetPathToAbsolutePath(RuntimeDataTypeAssetPath);
            if (!File.Exists(runtimeDataTypePath))
            {
                ShowError("未找到能力运行时数据类型定义，生成已中止。");
                return false;
            }

            string content = File.ReadAllText(runtimeDataTypePath);
            if (!content.Contains(RuntimeDataTypeGeneratedStartMarker) ||
                !content.Contains(RuntimeDataTypeGeneratedEndMarker))
            {
                ShowError("能力运行时数据类型定义缺少完整的自动生成区域，生成已中止。");
                return false;
            }

            if (ContainsReservedRuntimeDataType(content, abilityName) &&
                !ContainsGeneratedRuntimeDataType(content, abilityName))
            {
                ShowError($"能力名称 {abilityName} 与已有运行时数据键冲突，请更换能力名称。");
                return false;
            }

            return true;
        }

        /// <summary>判断运行时数据类型枚举是否已包含指定能力键。</summary>
        /// <param name="content">运行时数据类型枚举的完整源码。</param>
        /// <param name="abilityName">待检查的能力名称。</param>
        /// <returns>枚举已声明对应能力键时返回 true。</returns>
        private static bool ContainsRuntimeDataType(string content, string abilityName)
        {
            string entry = $"        {abilityName},";
            return content.Contains(entry);
        }

        /// <summary>判断枚举源码是否已经声明指定运行时数据键。</summary>
        /// <param name="content">运行时数据类型枚举的完整源码。</param>
        /// <param name="abilityName">待检查的能力名称。</param>
        /// <returns>源码任意位置已声明该键时返回 true。</returns>
        private static bool ContainsReservedRuntimeDataType(string content, string abilityName)
        {
            return ContainsRuntimeDataType(content, abilityName);
        }

        /// <summary>判断指定运行时数据键是否位于自动生成区域。</summary>
        /// <param name="content">运行时数据类型枚举的完整源码。</param>
        /// <param name="abilityName">待检查的能力名称。</param>
        /// <returns>键位于自动生成区域时返回 true。</returns>
        private static bool ContainsGeneratedRuntimeDataType(string content, string abilityName)
        {
            int startIndex = content.IndexOf(RuntimeDataTypeGeneratedStartMarker, StringComparison.Ordinal);
            int endIndex = content.IndexOf(RuntimeDataTypeGeneratedEndMarker, StringComparison.Ordinal);
            if (startIndex < 0 || endIndex <= startIndex) return false;

            int generatedContentStart = startIndex + RuntimeDataTypeGeneratedStartMarker.Length;
            string generatedContent = content.Substring(
                generatedContentStart,
                endIndex - generatedContentStart);
            return ContainsRuntimeDataType(generatedContent, abilityName);
        }

        /// <summary>将 Assets 资产路径转换为当前项目的绝对路径。</summary>
        private static string AssetPathToAbsolutePath(string assetPath)
        {
            string relativePath = assetPath.Substring("Assets".Length).TrimStart('/', '\\');
            return Path.GetFullPath(Path.Combine(Application.dataPath, relativePath));
        }

        /// <summary>选中并定位生成的能力文件夹。</summary>
        private static void SelectGeneratedFolder(string folderPath, string firstAssetPath)
        {
            UnityEngine.Object folder = AssetDatabase.LoadAssetAtPath<UnityEngine.Object>(folderPath);
            UnityEngine.Object target = folder ?? AssetDatabase.LoadAssetAtPath<UnityEngine.Object>(firstAssetPath);
            if (target == null) return;

            Selection.activeObject = target;
            EditorGUIUtility.PingObject(target);
        }

        /// <summary>显示创建流程错误并保留窗口供用户修正输入。</summary>
        private static void ShowError(string message)
        {
            Debug.LogError(message);
            EditorUtility.DisplayDialog("Create New Ability Scripts", message, "OK");
        }

        /// <summary>判断字符是否可以作为 C# 标识符首字符。</summary>
        private static bool IsIdentifierStart(char character)
        {
            return character == '_' || character >= 'A' && character <= 'Z' || character >= 'a' && character <= 'z';
        }

        /// <summary>判断字符是否可以作为 C# 标识符后续字符。</summary>
        private static bool IsIdentifierPart(char character)
        {
            return IsIdentifierStart(character) || character >= '0' && character <= '9';
        }

        // C# 关键字集合，用于阻止生成无法编译的类型名称。
        private static readonly HashSet<string> CSharpKeywords = new HashSet<string>(StringComparer.Ordinal)
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
            "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
            "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
            "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
            "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
            "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
            "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
            "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual",
            "void", "volatile", "while", "add", "alias", "ascending", "async", "await", "by", "descending",
            "dynamic", "equals", "from", "get", "global", "group", "into", "join", "let", "nameof",
            "notnull", "on", "orderby", "partial", "remove", "select", "set", "unmanaged", "value",
            "var", "when", "where", "with", "yield"
        };
    }
}
#endif
