namespace Framework.Gameplay.Abilities
{
    /// <summary>定义能力拥有者上下文中运行时数据的语义键。</summary>
    public enum AbilityRuntimeDataType
    {
        Input,
        Move,
        // 自动生成能力运行时数据时使用的专用键区域。
        // <auto-generated>
        Jump,
        Sprint,
        // </auto-generated>
    }
}
